'use client'
import { useEffect, useMemo, useState } from 'react'
import Sidebar from '../components/Sidebar'
type Application={id:string;openingTitle:string;type:string;applicantName:string;phone:string;email:string;address:string;guardianName:string;previousSchool:string;className:string;qualification:string;experience:string;subjects:string;documents:string;notes:string;submittedAt:string;status:'Pending'|'Approved'|'Rejected'}
export default function ApplicationsPage(){
 const [items,setItems]=useState<Application[]>([]),[filter,setFilter]=useState<'All'|'Pending'|'Approved'|'Rejected'>('Pending'),[selected,setSelected]=useState<Application|null>(null)
 useEffect(()=>{const raw=window.localStorage.getItem('gb-school-applications');if(raw)try{setItems(JSON.parse(raw))}catch{}},[])
 const counts=useMemo(()=>({pending:items.filter(x=>x.status==='Pending').length,approved:items.filter(x=>x.status==='Approved').length,rejected:items.filter(x=>x.status==='Rejected').length}),[items])
 const visible=items.filter(x=>filter==='All'||x.status===filter)
 const decide=(id:string,status:Application['status'])=>{const next=items.map(x=>x.id===id?{...x,status}:x);setItems(next);window.localStorage.setItem('gb-school-applications',JSON.stringify(next));setSelected(next.find(x=>x.id===id)||null)}
 return <div className="app-shell"><Sidebar/><main className="main"><p className="eyebrow">OWNER / ADMIN</p><div className="topline"><div><h1>Applications</h1><p className="muted">Review applications before onboarding.</p></div><a className="btn secondary" href="/apply">Open application form</a></div>
 <div className="grid grid3"><button className="card stat-filter" onClick={()=>setFilter('Pending')}><span className="muted">Pending</span><div className="stat">{counts.pending}</div></button><button className="card stat-filter" onClick={()=>setFilter('Approved')}><span className="muted">Approved</span><div className="stat">{counts.approved}</div></button><button className="card stat-filter" onClick={()=>setFilter('Rejected')}><span className="muted">Rejected</span><div className="stat">{counts.rejected}</div></button></div>
 <div className="card application-list-card"><div className="topline"><h3>Applications</h3><select aria-label="Application filter" value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option>Pending</option><option>Approved</option><option>Rejected</option><option>All</option></select></div>{visible.length===0?<div className="empty-state"><h3>No {filter.toLowerCase()} applications</h3><p className="muted">Submitted applications will appear here.</p></div>:<div className="application-table-wrap"><table className="table"><thead><tr><th>Applicant</th><th>Opening</th><th>Type</th><th>Submitted</th><th>Status</th><th></th></tr></thead><tbody>{visible.map(x=><tr key={x.id}><td><strong>{x.applicantName}</strong><br/><span className="muted">{x.phone}</span></td><td>{x.openingTitle}</td><td>{x.type}</td><td>{new Date(x.submittedAt).toLocaleDateString()}</td><td><span className="pill">{x.status}</span></td><td><button className="btn secondary" onClick={()=>setSelected(x)}>Review</button></td></tr>)}</tbody></table></div>}</div>
 {selected&&<div className="card application-detail"><div className="topline"><div><p className="eyebrow">APPLICATION REVIEW</p><h2>{selected.applicantName}</h2><p className="muted">{selected.openingTitle} · {selected.type}</p></div><button className="btn secondary" onClick={()=>setSelected(null)}>Close</button></div><div className="detail-grid"><div><strong>Contact</strong><p>{selected.phone}<br/>{selected.email||'No email provided'}</p></div><div><strong>Address</strong><p>{selected.address||'Not provided'}</p></div><div><strong>Background</strong><p>{selected.className||selected.qualification||'Not provided'}<br/>{selected.experience||''}{selected.subjects?<><br/>{selected.subjects}</>:null}</p></div><div><strong>Guardian / previous school</strong><p>{selected.guardianName||'Not provided'}<br/>{selected.previousSchool||''}</p></div><div><strong>Documents</strong><p>{selected.documents||'None listed.'}</p></div><div><strong>Additional information</strong><p>{selected.notes||'None provided.'}</p></div></div><div className="application-review-actions"><strong>Decision</strong><span className="pill">{selected.status}</span><button className="btn primary" onClick={()=>decide(selected.id,'Approved')}>Approve</button><button className="btn secondary" onClick={()=>decide(selected.id,'Rejected')}>Reject</button></div><p className="muted application-note">Decision only. Approval does not automatically create a student, teacher or staff account.</p></div>}
 </main></div>}
